<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_hpcanvas</name>
   <tag></tag>
   <elementGuidId>6d46a294-02f6-489f-ad13-3f01c9df34c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//canvas[@id='hpcanvas']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//canvas[@id='hpcanvas']</value>
   </webElementProperties>
</WebElementEntity>
